#!/bin/bash

read -p "MySQL Username [jamfsoftware]: " mysqluser
	mysqluser=${mysqluser:-jamfsoftware}
read -p "MySQL Password [jamfsw03]: " mysqlpassword
	mysqlpassword=${mysqlpassword:-jamfsw03}
read -p "Database Name [jamfsoftware]: "
echo ""

echo "application_usage_logs"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from application_usage_logs where computer_id not in (select computer_id from computers);"
echo "autorun_data"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from autorun_data where computer_id not in (select computer_id from computers);"
echo "available_software_updates"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from available_software_updates where computer_id not in (select computer_id from computers);"
echo "cached_packages"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from cached_packages where computer_id not in (select computer_id from computers);"
echo "computer_group_memberships"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from computer_group_memberships where computer_id not in (select computer_id from computers);"
echo "computer_installed_certificates"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from computer_installed_certificates where computer_id not in (select computer_id from computers);"
echo "computer_invitation_usage"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from computer_invitation_usage where computer_id not in (select computer_id from computers);"
echo "computer_previous_certificates"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from computer_previous_certificates where computer_id not in (select computer_id from computers);"
echo "computer_user_pushtokens"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from computer_user_pushtokens where computer_id not in (select computer_id from computers);"
echo "computers_denormalized"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from computers_denormalized where computer_id not in (select computer_id from computers);"
echo "file_vault_2_computer_key"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from file_vault_2_computer_key where computer_id not in (select computer_id from computers);"
echo "file_vault_2_users"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from file_vault_2_users where computer_id not in (select computer_id from computers);"
echo "ibook_volume_purchase_codes"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from ibook_volume_purchase_codes where computer_id not in (select computer_id from computers);"
echo "installed_printers"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from installed_printers where computer_id not in (select computer_id from computers);"
echo "licensed_software_usage"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from licensed_software_usage where computer_id not in (select computer_id from computers);"
echo "location_history"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from location_history where computer_id not in (select computer_id from computers);"
echo "logs"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from logs where computer_id not in (select computer_id from computers);"
echo "mac_app_volume_purchase_codes"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from mac_app_volume_purchase_codes where computer_id not in (select computer_id from computers);"
echo "mobile_device_details"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from mobile_device_details where computer_id not in (select computer_id from computers);"
echo "mobile_device_management_commands"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from mobile_device_management_commands where computer_id not in (select computer_id from computers);"
echo "os_x_configuration_profile_update_queue"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from os_x_configuration_profile_update_queue where computer_id not in (select computer_id from computers);"
echo "os_x_installed_configuration_profiles"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from os_x_installed_configuration_profiles where computer_id not in (select computer_id from computers);"
echo "package_receipts"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from package_receipts where computer_id not in (select computer_id from computers);"
echo "policy_history"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from policy_history where computer_id not in (select computer_id from computers);"
echo "pre_stage_logs"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from pre_stage_logs where computer_id not in (select computer_id from computers);"
echo "purchasing_information"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from purchasing_information where computer_id not in (select computer_id from computers);"
echo "reports"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from reports where computer_id not in (select computer_id from computers);"
echo "running_services"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from running_services where computer_id not in (select computer_id from computers);"
echo "software_id_license_linkage_activation_statuses"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from software_id_license_linkage_activation_statuses where computer_id not in (select computer_id from computers);"
echo "software_id_license_linkage_channel_types"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from software_id_license_linkage_channel_types where computer_id not in (select computer_id from computers);"
echo "software_id_license_linkage_customer_types"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from software_id_license_linkage_customer_types where computer_id not in (select computer_id from computers);"
echo "software_id_tags"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from software_id_tags where computer_id not in (select computer_id from computers);"
echo "task_assignments"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from task_assignments where computer_id not in (select computer_id from computers);"
echo "usage_logs"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from usage_logs where computer_id not in (select computer_id from computers);"
echo "user_receipts"
mysql -u $mysqluser -p$mysqlpassword --database $database -e "select count(*) from user_receipts where computer_id not in (select computer_id from computers);"